export const countryData = [
    { text: 'Afghanistan', value: '200' },
    { text: 'Albania', value: '401' },
    { text: 'Algeria', value: '100' },
    { text: 'Andorra', value: '402' },
    { text: 'Angola', value: '101' },
    { text: 'Antigua and Barbuda', value: '500' },
    { text: 'Argentina', value: '520' },
    { text: 'Armenia', value: '201' },
    { text: 'Australia', value: '300' },
    { text: 'Austria', value: '403' },
    { text: 'Azerbaijan', value: '202' },
    { text: 'Bahamas', value: '501' },
    { text: 'Bahrain', value: '203' },
    { text: 'Bangladesh', value: '204' },
    { text: 'Barbados', value: '502' },
    { text: 'Belarus', value: '404' },
    { text: 'Belgium', value: '405' },
    { text: 'Belize', value: '503' },
    { text: 'Benin', value: '102' },
    { text: 'Bhutan', value: '205' },
    { text: 'Bolivia', value: '521' },
    { text: 'Bosnia and Herzegovina', value: '406' },
    { text: 'Botswana', value: '103' },
    { text: 'Brazil', value: '522' },
    { text: 'Brunei', value: '206' },
    { text: 'Bulgaria', value: '407' },
    { text: 'Burkina Faso', value: '104' },
    { text: 'Burundi', value: '105' },
    { text: 'Cabo Verde', value: '106' },
    { text: 'Cambodia', value: '207' },
    { text: 'Cameroon', value: '107' },
    { text: 'Canada', value: '504' },
    { text: 'Central African Republic', value: '108' },
    { text: 'Chad', value: '109' },
    { text: 'Chile', value: '523' },
    { text: 'China', value: '208' },
    { text: 'Colombia', value: '524' },
    { text: 'Comoros', value: '110' },
    { text: 'Congo', value: '111' },
    { text: 'Costa Rica', value: '505' },
    { text: 'Croatia', value: '408' },
    { text: 'Cuba', value: '506' },
    { text: 'Cyprus', value: '400' },
    { text: 'Czech Republic', value: '409' },
    { text: 'Denmark', value: '410' },
    { text: 'Djibouti', value: '112' },
    { text: 'Dominica', value: '507' },
    { text: 'Dominican Republic', value: '508' },
    { text: 'East Timor ', value: '209' },
    { text: 'Ecuador', value: '525' },
    { text: 'Egypt', value: '113' },
    { text: 'El Salvador', value: '509' },
    { text: 'Equatorial Guinea', value: '114' },
    { text: 'Eritrea', value: '115' },
    { text: 'Estonia', value: '411' },
    { text: 'Eswatini', value: '116' },
    { text: 'Ethiopia', value: '117' },
    { text: 'Fiji', value: '301' },
    { text: 'Finland', value: '412' },
    { text: 'France', value: '413' },
    { text: 'Gabon', value: '118' },
    { text: 'Gambia', value: '119' },
    { text: 'Georgia', value: '210' },
    { text: 'Germany', value: '414' },
    { text: 'Ghana', value: '120' },
    { text: 'Greece', value: '415' },
    { text: 'Grenada', value: '510' },
    { text: 'Guatemala', value: '511' },
    { text: 'Guinea', value: '121' },
    { text: 'Guinea-Bissau', value: '122' },
    { text: 'Guyana', value: '526' },
    { text: 'Haiti', value: '512' },
    { text: 'Honduras', value: '513' },
    { text: 'Hungary', value: '416' },
    { text: 'Iceland', value: '417' },
    { text: 'India', value: '211' },
    { text: 'Indonesia', value: '212' },
    { text: 'Iran', value: '213' },
    { text: 'Iraq', value: '214' },
    { text: 'Ireland', value: '418' },
    { text: 'Israel', value: '215' },
    { text: 'Italy', value: '419' },
    { text: 'Jamaica', value: '514' },
    { text: 'Japan', value: '216' },
    { text: 'Jordan', value: '217' },
    { text: 'Kazakhstan', value: '218' },
    { text: 'Kenya', value: '123' },
    { text: 'Kiribati', value: '302' },
    { text: 'Kosovo', value: '420' },
    { text: 'Kuwait', value: '219' },
    { text: 'Kyrgyzstan', value: '220' },
    { text: 'Laos', value: '221' },
    { text: 'Latvia', value: '421' },
    { text: 'Lebanon', value: '222' },
    { text: 'Lesotho', value: '124' },
    { text: 'Liberia', value: '125' },
    { text: 'Libya', value: '126' },
    { text: 'Liechtenstein', value: '422' },
    { text: 'Lithuania', value: '423' },
    { text: 'Luxembourg', value: '424' },
    { text: 'Macedonia ', value: '425' },
    { text: 'Malawi', value: '127' },
    { text: 'Malaysia', value: '223' },
    { text: 'Maldives', value: '224' },
    { text: 'Mali', value: '128' },
    { text: 'Malta', value: '426' },
    { text: 'Marshall Islands', value: '303' },
    { text: 'Mauritania', value: '129' },
    { text: 'Mauritius', value: '130' },
    { text: 'Mexico', value: '515' },
    { text: 'Micronesia', value: '304' },
    { text: 'Moldova', value: '427' },
    { text: 'Monaco', value: '428' },
    { text: 'Mongolia', value: '225' },
    { text: 'Montenegro', value: '429' },
    { text: 'Morocco', value: '131' },
    { text: 'Mozambique', value: '132' },
    { text: 'Myanmar ', value: '226' },
    { text: 'Namibia', value: '133' },
    { text: 'Nauru', value: '305' },
    { text: 'Nepal', value: '227' },
    { text: 'Netherlands', value: '430' },
    { text: 'New Zealand', value: '306' },
    { text: 'Niger', value: '134' },
    { text: 'Nigeria', value: '135' },
    { text: 'North Korea', value: '228' },
    { text: 'Norway', value: '431' },
    { text: 'Oman', value: '229' },
    { text: 'Pakistan', value: '230' },
    { text: 'Palau', value: '307' },
    { text: 'Panama', value: '516' },
    { text: 'Papua New Guinea', value: '308' },
    { text: 'Paraguay', value: '527' },
    { text: 'Peru', value: '528' },
    { text: 'Philippines', value: '231' },
    { text: 'Poland', value: '432' },
    { text: 'Portugal', value: '433' },
    { text: 'Qatar', value: '232' },
    { text: 'Republic of the Congo', value: '136' },
    { text: 'Romania', value: '434' },
    { text: 'Russia', value: '442' },
    { text: 'Rwanda', value: '137' },
    { text: 'Saint Kitts and Nevis', value: '517' },
    { text: 'Saint Lucia', value: '518' },
    { text: 'Samoa', value: '309' },
    { text: 'San Marino', value: '435' },
    { text: 'Saudi Arabia', value: '233' },
    { text: 'Senegal', value: '138' },
    { text: 'Serbia', value: '436' },
    { text: 'Seychelles', value: '139' },
    { text: 'Sierra Leone', value: '140' },
    { text: 'Singapore', value: '234' },
    { text: 'Somalia', value: '141' },
    { text: 'South Africa', value: '142' },
    { text: 'South Korea', value: '235' },
    { text: 'South Sudan', value: '143' },
    { text: 'Spain', value: '437' },
    { text: 'Sri Lanka', value: '236' },
    { text: 'Sudan', value: '144' },
    { text: 'Sweden', value: '438' },
    { text: 'Switzerland', value: '439' },
    { text: 'Syria', value: '237' },
    { text: 'Taiwan', value: '238' },
    { text: 'Tajikistan', value: '239' },
    { text: 'Tanzania', value: '145' },
    { text: 'Thailand', value: '240' },
    { text: 'Togo', value: '146' },
    { text: 'Tunisia', value: '147' },
    { text: 'Turkey', value: '443' },
    { text: 'Turkmenistan', value: '241' },
    { text: 'Tuvalu', value: '310' },
    { text: 'Uganda', value: '148' },
    { text: 'Ukraine', value: '440' },
    { text: 'United Arab Emirates', value: '242' },
    { text: 'United Kingdom', value: '441' },
    { text: 'United States', value: '519' },
    { text: 'Uzbekistan', value: '243' },
    { text: 'Venezuela', value: '529' },
    { text: 'Vietnam', value: '244' },
    { text: 'Yemen', value: '245' },
    { text: 'Zambia', value: '149' },
    { text: 'Zimbabwe', value: '150' }
    

  ];
  
  export const aupairCountryData = [
    { text: 'Australia', value: '300' },
    { text: 'Austria', value: '403' },
    { text: 'Belgium', value: '405' },
    { text: 'Canada', value: '504' },
    { text: 'China', value: '208' },
    { text: 'Czech Republic', value: '409' },
    { text: 'Denmark', value: '410' },
    { text: 'Finland', value: '412' },
    { text: 'France', value: '413' },
    { text: 'Germany', value: '414' },
    { text: 'Greece', value: '415' },
    { text: 'Hungary', value: '416' },
    { text: 'Iceland', value: '417' },
    { text: 'Ireland', value: '418' },
    { text: 'Italy', value: '419' },
    { text: 'Luxembourg', value: '424' },
    { text: 'Malta', value: '426' },
    { text: 'Netherlands', value: '430' },
    { text: 'New Zealand', value: '306' },
    { text: 'Norway', value: '431' },
    { text: 'Poland', value: '432' },
    { text: 'Portugal', value: '433' },
    { text: 'Spain', value: '437' },
    { text: 'Sweden', value: '438' },
    { text: 'Switzerland', value: '439' },
    { text: 'Turkey', value: '443' },
    { text: 'United Kingdom', value: '441' },
    { text: 'United States', value: '519' }
    

  ];

  export const languageData = [
    { text: 'Arabic', value: '1' },
    { text: 'Chinese', value: '2' },
    { text: 'Czech', value: '3' },
    { text: 'Danish', value: '4' },
    { text: 'Dutch', value: '5' },
    { text: 'English', value: '6' },
    { text: 'Finnish', value: '7' },
    { text: 'French', value: '8' },
    { text: 'German', value: '9' },
    { text: 'Hindi', value: '10' },
    { text: 'Italian', value: '11' },
    { text: 'Japanese', value: '12' },
    { text: 'Maltese', value: '13' },
    { text: 'Norwegian', value: '14' },
    { text: 'Polish', value: '15' },
    { text: 'Portuguese', value: '16' },
    { text: 'Russian', value: '17' },
    { text: 'Spanish', value: '18' },
    { text: 'Swedish', value: '19' },
    { text: 'Turkish', value: '20' },
    { text: 'Ukrainian', value: '21' },

  ];
  
  
  


 export const monthData = [
{ text: 'January', value: '1' },
{ text: 'February', value: '2' },
{ text: 'March', value: '3' },
{ text: 'April', value: '4' },
{ text: 'May', value: '5' },
{ text: 'June', value: '6' },
{ text: 'July', value: '7' },
{ text: 'August', value: '8' },
{ text: 'September', value: '9' },
{ text: 'October', value: '10' },
{ text: 'November', value: '11' },
{ text: 'December', value: '12' },
  ];

  export const hostKidAgeGroupData = [
    { text: '0-1 years', value: '1' },
    { text: '1-5 years', value: '2' },
    { text: '5-10 years', value: '3' },
    { text: '10-15 years', value: '4' },
    { text: '15+ years', value: '5' },
];

export const educationData = [
    { text: 'High School Diploma', value: '1' },
    { text: 'Bachelor Degree', value: '2' },
    { text: 'Master Degree', value: '3' },
    { text: 'Vocational training', value: '4' },
    { text: 'Others', value: '5' },
];

export const durationOfStayData = [
    { text: '1-3 months', value: '1' },
    { text: '3-6 months', value: '2' },
    { text: '6-9 months', value: '3' },
    { text: '9-12 months', value: '4' },
    { text: '12-24 months', value: '5' },
];
  export function yearData(startYear: number, endYear: number): number[] {
    const years: number[] = [];
    for (let year = startYear; year <= endYear; year++) {
      years.push(year);
    }
    return years;
  }

  export function numberData(startnumber: number, endNumber: number): number[] {
    const numbers: number[] = [];
    for (let num = startnumber; num <= endNumber; num++) {
      numbers.push(num);
    }
    return numbers;
  }

  